//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.gov.sg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduates_From_University
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public string Sex { get; set; }
        public string TypeOfCourse { get; set; }
        public int NoOfGraduates { get; set; }
    }
}
